[package]
name = "iso_add_countries"
version = "0.1.0"
authors = ["Paul Bacchus <paul@paulbacchus.com>"]

[dependencies]
regex = "1.5.5"
serde = "1.0.71"
serde_json = "1.0.24"
serde_derive = "1.0.71"
lazy_static = "1.1.0"