[package]
name = "parse_pages"
version = "0.3.0"
authors = ["Paul Bacchus <paul@paulbacchus.com>"]

[dependencies]
types = {path = "../types"}
scraper = "0.6.0"
regex = "0.2"
lazy_static = "1.0.1"
serde = "1.0.66"
serde_json = "1.0.19"