[package]
name = "add_countries"
version = "0.1.0"
authors = ["Paul Bacchus <paul@paulbacchus.com>"]

[dependencies]
reqwest = "0.8.7"
scraper = "0.7.0"
regex = "1.0.2"
serde = "1.0.71"
serde_json = "1.0.24"
serde_derive = "1.0.71"
rayon = "1.0.2"
lazy_static = "1.1.0"